---
# tasks file for azurecapability

- name: linux commands 
  when: ansible_system == "Linux"
  ansible.builtin.include_tasks:
    file: Linux/main.yml


# - name: windows commands 
#   when: ansible_os_family == "Windows"
#   ansible.builtin.include_tasks:
#     file: Windows/main.yml