---


  - name: Retrive secret
    ansible.windows.win_uri:
      url: "https://{{ item.vault }}.{{ item.base_url | default('vault.azure.net') }}/secrets/{{ item.secret }}?api-version={{ item.api_version | default('2016-10-01') }}"
      method: GET
      return_content: true
      headers:
        Authorization: "Bearer {{ token_directive.json.access_token }}"
    register: secret

  - name: output secret
    debug:
      msg: "{{ secret.json.value }}"


# outputs 
  - name: Set an environment variable for secret
    when: item.output_env is defined
    ansible.windows.win_environment:
      state: present
      name: "{{ item.output_env }}"
      value: "{{ secret.json.value }}"
      level: machine

  - name: Set the contents of a file "{{ item.output_path }}" to secret
    when: item.output_path is defined
    ansible.windows.win_copy:
      content: "{{ secret.json.value }}"
      dest: "{{ item.output_path }}"
