---


  - name: Retrive secret
    ansible.windows.win_uri:
      url: "{{ azure_key_vault.key_vault_url }}/secrets/{{ azure_key_vault.secrets_name }}?api-version=2016-10-01"
      method: GET
      return_content: true
      headers:
        Authorization: "Bearer {{ token_directive.json.access_token }}"
    register: secret

  - name: output secret
    debug:
      msg: "{{ secret.json.value }}"
