---


  - name: Retrive key
    ansible.builtin.uri:
      url: "https://{{ item.vault }}.vault.azure.net/keys/{{ azure_key_vault.key_name }}?api-version=2016-10-01"
      method: GET
      return_content: true
      headers:
        Authorization: "Bearer {{ token_directive.json.access_token }}"
    register: key

  - name: output secret
    debug:
      msg: "{{ key.json.key }}"
