---


  - name: Retrive key
    ansible.builtin.uri:
      url: "https://{{ item.vault }}.{{ item.base_url | default('vault.azure.net') }}/keys/{{ item.key }}?api-version={{ item.api_version | default('2016-10-01') }}"
      method: GET
      return_content: true
      headers:
        Authorization: "Bearer {{ token_directive.json.access_token }}"
    register: key

  - name: output secret
    debug:
      msg: "{{ key.json.key }}"


  - name: Settting perment env for "{{ item.output_env }}"
    when: item.output_env is defined
    become: true
    block:
      - name: Adding the path in the Profile files
        lineinfile: 
          dest: /etc/environment
          line: 'export {{ item.output_env }}="{{ key.json.key }}"' 
          insertafter: EOF
          state: present

      - name: Source the bash_profile file
        shell: source /etc/environment


  - name: Set the contents of a file "{{ item.output_path }}" to key
    when: item.output_path is defined
    ansible.builtin.copy:
      content: "{{ key.json.key }}"
      dest: "{{ item.output_path }}"
